services:
  postgres:
    image: postgres:15-alpine
    container_name: taskmanager-postgres
    environment:
      POSTGRES_DB: taskmanager
      POSTGRES_USER: taskmanager_user
      POSTGRES_PASSWORD: taskmanager_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U taskmanager_user -d taskmanager"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: taskmanager-app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/taskmanager
      SPRING_DATASOURCE_USERNAME: taskmanager_user
      SPRING_DATASOURCE_PASSWORD: taskmanager_password
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: false
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

volumes:
  postgres_data: 